version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/staff
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - staff-manager-network

  file-export:
    build:
      context: .
      dockerfile: file-export/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/staff
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - FILE_EXPORT_API_EMPLOYEES_URL=http://api-gateway:9090/api/v1/employees
    depends_on:
      - db
      - api-gateway
    networks:
      - staff-manager-network

  db:
    image: postgres:11.22-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: staff
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - staff-manager-network

networks:
  staff-manager-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local