server:
  port: 9090

app:
  swagger-url: http://localhost:9090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://db:5432/staff
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
